---
# Install and configure nginx

- name: install nginx server
  apt: name=nginx-full state=present

- name: create configuration file for chalupas site
  template: src=nginx-chalupas.site.j2 dest=/etc/nginx/sites-available/{{ chalupas_server_name }}
  notify: reload nginx

- name: enable chalupas site
  file: src=/etc/nginx/sites-available/{{ chalupas_server_name }} dest=/etc/nginx/sites-enabled/{{ chalupas_server_name }} state=link
  notify: reload nginx
