language: python
python:
  - "2.7"
  - "3.4"
install: "python setup.py install"
script: "python setup.py test"
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/1.13.2/pandoc-1.13.2-1-amd64.deb
  - sudo dpkg -i pandoc-1.13.2-1-amd64.deb
